services:
  # Service: build base core image (CE/EE)
  odoo-core:
    build:
      context: .
      dockerfile: base/Dockerfile
      args:
        ODOO_EDITION: ${ODOO_EDITION:-ce} # ce (Odoo Community Edition) or ee (Odoo Enterprise Edition)

        # For Enterprise private repository authentication (default values are for Github)
        ODOO_EE_GIT_USER: ${GITHUB_USER:-x-access-token}
        ODOO_EE_GIT_TOKEN: ${GITHUB_TOKEN:-}
        ODOO_EE_GIT_HOST: ${GITHUB_HOST:-github.com}

        # If you want to use your own git host for ee addons, you can change the values in .env file
        # ODOO_EE_GIT_USER: ${GIT_USER:-x-access-token} # Git host personal access token user
        # ODOO_EE_GIT_TOKEN: ${GIT_TOKEN:-} # Git host personal access token token
        # ODOO_EE_GIT_HOST: ${GIT_HOST:-github.com} # Git host (e.g. github.com, gitlab.com, etc.)

        # Optional Arguments (you can change default values if needed just uncomment and change the values in .env file)
        ODOO_CE_VERSION: ${ODOO_CE_VERSION:-${ODOO_VERSION:-18.0}} # CE series/tag used as a fallback
        ODOO_CE_REF: ${ODOO_CE_REF:-${ODOO_CE_VERSION:-${ODOO_VERSION:-18.0}}} # CE branch/tag/commit to fetch
        ODOO_EE_VERSION: ${ODOO_EE_VERSION:-${ODOO_VERSION:-18.0}} # EE series/tag used as a fallback
        ODOO_ENTERPRISE_REF: ${ODOO_ENTERPRISE_REF:-${ODOO_EE_VERSION:-${ODOO_VERSION:-18.0}}} # EE branch/tag/commit to fetch
        ODOO_EE_ADDONS_DIR: ${ODOO_EE_ADDONS_DIR:-/opt/enterprise-addons} # EE addons directory
        ODOO_ENTERPRISE_REPO: ${ODOO_ENTERPRISE_REPO:-https://github.com/odoo/enterprise.git} # EE repository URL
        ODOO_LOG_DIR: ${ODOO_LOG_DIR:-/var/log/odoo} # Odoo log directory
        EXTRA_ADDONS_DIR: ${EXTRA_ADDONS_DIR:-/opt/extra-addons} # Extra addons directory
        POSTGRES_VERSION: ${POSTGRES_VERSION:-16} # PostgreSQL client version
    image: odoo-core-${ODOO_EDITION:-ce}:${ODOO_VERSION:-18.0}
    profiles: ["build"]

  odoo:
    image: odoo-${ODOO_EDITION:-ce}:${ODOO_VERSION:-18.0}
    build:
      context: .
      dockerfile: addons/Dockerfile
      args:
        BASE_IMAGE: odoo-core-${ODOO_EDITION:-ce}:${ODOO_VERSION:-18.0}
    environment:
      ODOO_ENV_FILE: "/run/odoo/.env"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./.env:/run/odoo/.env:ro # Environment variables file for generating Odoo config file and extra addons installation (for private repository authentication)
      - odoo-data:/var/lib/odoo
      - ${LOCAL_ADDONS_DIR:-./local-addons}:/opt/local-addons
    restart: unless-stopped

  caddy:
    image: caddy:2.8.4-alpine
    depends_on:
      - odoo
    environment:
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - CADDY_EMAIL=${CADDY_EMAIL}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
  odoo-data:
  caddy-data:
  caddy-config:
